import type { Metadata } from "next";
import localFont from "next/font/local";
import { Nunito_Sans} from 'next/font/google'
import "./globals.css";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito.variable}>
      <body
       className="font-nunito antialiased"
      >
        {children}
      </body>
    </html>
  );
}
